// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxvszdkbqxzzpksbyflf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54dnN6ZGticXh6enBrc2J5ZmxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTI1NzEsImV4cCI6MjA2MDgyODU3MX0.SGh6BcP3yx_blkxfdf67dbheXcmQk9uSHiv1ummF1WY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);